# Generated by Django 3.2.6 on 2021-08-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.todolist'),
        ),
        migrations.DeleteModel(
            name='Call',
        ),
    ]
