# Generated by Django 3.2.6 on 2021-08-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_auto_20210818_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=400)),
                ('subject', models.CharField(max_length=200)),
                ('date_field', models.DateTimeField(max_length=20)),
                ('time_field', models.CharField(max_length=20)),
                ('problem_description', models.CharField(max_length=600)),
                ('comment', models.CharField(max_length=500)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
