# Generated by Django 3.2.6 on 2021-08-25 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_alter_callback_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
