# Generated by Django 3.2.6 on 2021-08-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_callback_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='date_field',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='callback',
            name='time_field',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
